version: "3.8"
services:
  nextjs-blog:
    container_name: nextjs-blog
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./blog
        target: /blog
    command: bash -c "cd app && yarn dev"
